name: Applyforme

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:

  Test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend

    steps: 
      - uses: actions/checkout@v2
        with:
          script: |
            touch test
            cd /home/ubuntu/actions


    # - name: Build
    #   run: npm run build
      
    # - name: test
    #   run: npm test

  # deploy:
  #   name: deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to server
  #       uses: appleboy/ssh-action@master
    
  #       env:
  #         GITHUB_USERNAME: ${{ secrets.VICDAM_USER }}  
  #         GITHUB_TOKEN: ${{ secrets.VICDAM_TOKEN }}     
  #         host: ${{ secrets.HNG_SERVER_HOST }}          
  #         username: ${{ secrets.HNG_SERVER_USERNAME }}
  #         password: ${{ secrets.HNG_SERVER_PASSWORD }}
  #         port: ${{ secrets.HNG_SERVER_PORT }}

  #       with:
  #         host: ${{ secrets.HNG_SERVER_HOST }}          
  #         username: ${{ secrets.HNG_SERVER_USERNAME }}
  #         password: ${{ secrets.HNG_SERVER_PASSWORD }}
  #         port: ${{ secrets.HNG_SERVER_PORT }}
  #         script: |
  #           cd applyforme/applyforme.web/
  #           git pull
  #           pm2 restart backend
  #           cd ./Apply-For-Me-UI
  #           npm install
  #           pm2 restart npm
  #           pm2 save
     